### ISSUE TITLE
Wait what?

### ISSUE THREAD

**Issue by david4096** [julianwachholz/lynch#1]

**Comment by julianwachholz** [comment]
Yes?

**Comment by david4096** [comment]
Can you say more about what inspired you to make this game?

**Comment by julianwachholz** [comment]
It's far from finished (iirc at the moment it's just a barebones lobby) but the recent Town of Salem Kickstarter originally got me to start this.

Maybe I should someday finish this.

**Comment by david4096** [comment]
It just seemed like frighteningly racist

**Comment by julianwachholz** [comment]
I'm sorry you feel that way.
